[features]
seeds = false
skip-lint = false

[programs.localnet]
solscore_new = "2G2gUi3YjhJoziTg4xqeKoB2Y7ReJLUsw52gqYn9FeSP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/udoka/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
# You may need specific toolchain settings here